version: '3.8'

services:

  app:
    build:
      context: .
    image: wallet
    container_name: wallet-service
    environment:
      SPRING_APPLICATION_NAME: javacode-wallet-management
      SPRING_SQL_INIT_MODE: always
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT: DEBUG
      SPRING_JPA_SHOW_SQL: "true"
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL: TRACE
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/2024/08/20-01-changelog.xml
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet_db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: walletdb_user
      SPRING_DATASOURCE_PASSWORD: wallet
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: wallet_db
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: walletdb_user
      POSTGRES_PASSWORD: wallet
    ports:
      - "6541:5432"

